import { BaseNodeHandler, ExecutionContext } from "./BaseNodeHandler";
import { executeNodeRequest } from "../../engine";
import { AgentType } from "../types";

export class TTSHandler extends BaseNodeHandler {
  public async execute(context: ExecutionContext): Promise<string> {
    const { node, nodeId, finalUserInput, upstreamContext, nodeModel, supabase } = context;

    // Reserve a media call (throws if budget exceeded)
    const callNum = context.reserveMediaCall();

    const rawTextResult = await executeNodeRequest(node.type as AgentType, finalUserInput, upstreamContext, "qwen", nodeModel, { targetLanguage: context.language, videoDuration: context.videoDuration });
    
    // Clean up any introductory labels or prefixes often generated by LLMs (e.g. "Narasi untuk sintesis suara:")
    let cleanText = rawTextResult
      .replace(/^.*?(?:narasi|narration|voice\s*over|vo|speech|sintesis|teks|format)[^:]*:\s*/i, "")
      .replace(/^["']|["']$/g, "")
      .trim();
    if (!cleanText) cleanText = rawTextResult.trim();

    console.log(`[ServerEngine] Generating TTS for ${nodeId} with clean text: "${cleanText.slice(0, 50)}..." (media call #${callNum})`);
    
    const { DashScopeMedia } = await import("../../ai/providers/DashScopeMedia");
    const audioUrl = await DashScopeMedia.generateAudio(cleanText, context.language);
    
    let finalAudioUrl = audioUrl;
    try {
      const { CloudflareR2 } = await import("../../cloud/CloudflareR2");
      const res = await CloudflareR2.uploadMedia(audioUrl, "tts-audio");
      finalAudioUrl = res.url;
    } catch (e) { 
      console.warn(`[ServerEngine] TTS ${nodeId}: R2 upload fallback`);
    }

    await supabase.from("nodes").update({ output_url: finalAudioUrl, output: cleanText }).eq("id", nodeId);
    
    return cleanText;
  }
}
